### ISSUE TITLE
Android Code

### ISSUE THREAD

**Issue by amoghbl1** [wavesplatform/WavesWallet-android#1]
Hey guys, I see that you have this repo to upload the code relate to [waves wallet android](https://play.google.com/store/apps/details?id=com.wavesplatform.wallet&hl=en).
I'd love to check out this project and maybe contribute some code in my free time, so could you please let me know when you plan on actually making this public?
Love the platform, keep up the good work 👍

**Comment by koloale** [comment]
It has been made open source.
