### ISSUE TITLE
can't pull up custom tokens

### ISSUE THREAD

**Issue by sabotagebeats** [wavesplatform/WavesWallet-android#14]
only verified tokens show up in the search even when the token id is pasted in the search

**Comment by ericelliott** [comment]
I was able to find and select tokens I created using 2.0.0 (409)

May be intermitent? Network issues?

**Comment by ZaydelEduard** [comment]
@sabotagebeats Most likely you used the old version (1.1.6). There was the possibility of switching between verified and non-verifiable assets. Try using the current version of the master (2.0.0) or develop (2.0.1) and check your problem. (To display spam tokens in the list of markets - disable filtering in the profile settings). Thanks. Waiting for your answer.
