### ISSUE TITLE
How to get free Ether Tokens on Waves for TestNet - Debug Test ?

### ISSUE THREAD

**Issue by ethaan100** [wavesplatform/WavesWallet-android#237]
Currently am able to get Free Waves Tokens from Waves Faucet. 
Now for debugging purpose ow can I get free Ether Tokens on Waves for TestNet ?

The Ethereum address (0x...) generated after wallet creation is done by which package ? I have some Ethers on Ropsten Testnet. Can I send it to Waves Ether address for testing purpose or this Ether address is only working from Main Ethereum network. Is there any dependency from Coinomat over here. I can see in Environment_testnet.json file "isGateway=true" has been mentioned .
Can you please suggest on this.

**Comment by ZaydelEduard** [comment]
Hello @ethaan100 

The only way to get ETH on Test Net - buy on Test Net DEX

**Comment by ZaydelEduard** [comment]
Any update here? 
Will close tommorow if the issue is not relevant

**Comment by ZaydelEduard** [comment]
I close the issue because of inactivity (no relevance). If there is something new here - open again.
