### ISSUE TITLE
Cant withdraw ether

### ISSUE THREAD

**Issue by Rottbrand** [wavesplatform/WavesWallet-android#371]
![photo5310127849597938610](https://user-images.githubusercontent.com/5114184/61643499-4e035a00-aca3-11e9-9e4c-0d6c5acd410d.jpg)

**Comment by ZaydelEduard** [comment]
Hello @Rottbrand 

The problem is actual? 

Try to download the latest version of the app in the Play Market and try to withdraw ETH again. 

Thanks

**Comment by Rottbrand** [comment]
Hi @ZaydelEduard 
no the problem was temporary because coinomat service failed. There was a detailed error message about it in the desktop app. Would be better if both show the same.

**Comment by ZaydelEduard** [comment]
Thanks for your feedback. Messages from gateways is planned to be added soon!
