### ISSUE TITLE
run with ERROR: Could not read script '/Users/.../WavesWallet-android/app/api-keys.properties' as it does not exist.

### ISSUE THREAD

**Issue by bianxiang** [wavesplatform/WavesWallet-android#391]
run with ERROR: Could not read script '/Users/.../WavesWallet-android/app/api-keys.properties' as it does not exist.

![image](https://user-images.githubusercontent.com/16380379/63142354-12e31500-c01c-11e9-82aa-15fff66bcd64.png)

**Comment by ZaydelEduard** [comment]
Hello @bianxiang 

Create file and name it as `api-keys.properties` inside `.../WavesWallet-android/app` folder

Then add this lines and paste your `token` from services indead of `YOUR_TOKEN_HERE`

```
ext.appsFlyerKey="YOUR_TOKEN_HERE"
ext.fabricApiKey="YOUR_TOKEN_HERE"
ext.devAmplitudeApiKey="YOUR_TOKEN_HERE"
ext.prodAmplitudeApiKey="YOUR_TOKEN_HERE"
```

Run! Profit!

**Comment by ZaydelEduard** [comment]
Any update here? 
Will close tommorow if the issue is not relevant

**Comment by ZaydelEduard** [comment]
I close the issue because of inactivity (no relevance). If there is something new here - open again.
