### ISSUE TITLE
cannot resolve symbol DaggerApplicationV2Component

### ISSUE THREAD

**Issue by bianxiang** [wavesplatform/WavesWallet-android#392]
![image](https://user-images.githubusercontent.com/16380379/63157861-86038000-c04a-11e9-9d55-6a763b05d38d.png)

**Comment by ZaydelEduard** [comment]
Hello @bianxiang 

This class will be generated on build time via dagger code generation

**Comment by ZaydelEduard** [comment]
Any update here? 
Will close tommorow if the issue is not relevant

**Comment by ZaydelEduard** [comment]
I close the issue because of inactivity (no relevance). If there is something new here - open again.
