### ISSUE TITLE
when I restart my mac,this android project deleted from my mac automaticly,it happed twice

### ISSUE THREAD

**Issue by bianxiang** [wavesplatform/WavesWallet-android#394]

**Comment by ZaydelEduard** [comment]
Hello @bianxiang 

Has nothing to do with the project, a problem on your side related to the MacBook or something else

**Comment by bianxiang** [comment]
ok,I Check it again

**Comment by ZaydelEduard** [comment]
Any update here? 
Will close tommorow if the issue is not relevant

**Comment by ZaydelEduard** [comment]
I close the issue because of inactivity (no relevance). If there is something new here - open again.
