### ISSUE TITLE
Task :WavesSDK-android:wavesplatform:kaptDebugKotlin FAILED

### ISSUE THREAD

**Issue by bianxiang** [wavesplatform/WavesWallet-android#395]
![image](https://user-images.githubusercontent.com/16380379/63165512-43e43980-c05e-11e9-85f8-a2a08ab1a594.png)
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':WavesSDK-android:wavesplatform:kaptDebugKotlin'.
> Internal compiler error. See log for more details

**Comment by ZaydelEduard** [comment]
Hello @bianxiang 

I think that problem of Java that installed on your local machine, maybe not correct version. Need Java 1.8

**Comment by ZaydelEduard** [comment]
Any update here? 
Will close tommorow if the issue is not relevant

**Comment by ZaydelEduard** [comment]
I close the issue because of inactivity (no relevance). If there is something new here - open again.
