### ISSUE TITLE
I changed firebase to local database, it keeps “Geen verbinding met het internet”,I am closed vpn

### ISSUE THREAD

**Issue by bianxiang** [wavesplatform/WavesWallet-android#401]
![image](https://user-images.githubusercontent.com/16380379/63259881-29a29980-c2b2-11e9-9fef-74f971fe4854.png)
I changed remote firebase to local database, it keeps “Geen verbinding met het internet”,I am closed vpn,but I delete all of the code related to firebase，why？

**Comment by bianxiang** [comment]
I see you used ReactiveNetwork，but I check my network is conecting,can browse other htmlPage

**Comment by ZaydelEduard** [comment]
Hello @bianxiang 

Try to switch your internet connection to Wi-fi or Mobile Network. Maybe problem with your internet observer.

**Comment by bianxiang** [comment]
Because some area can not connect to firebase,I changed firebase to local database ，base on version 2.5，see this url
👉[https://github.com/bianxiang/WavesWallet-Android-FirebaseRemoved](https://github.com/bianxiang/WavesWallet-Android-FirebaseRemoved)

**Comment by ZaydelEduard** [comment]
Use VPN to connect with Firebase.

Any update here? 
Will close tommorow if the issue is not relevant

**Comment by ZaydelEduard** [comment]
I close the issue because of inactivity (no relevance). If there is something new here - open again.
