### ISSUE TITLE
Payment API

### ISSUE THREAD

**Issue by bodrych** [wavesplatform/WavesWallet-android#406]
It would be great to add [deep link](https://developer.android.com/training/app-links/deep-linking.html) to handle [payment api](https://docs.wavesplatform.com/en/waves-api-and-sdk/client-api/payments-api.html) link in app [manifest](https://github.com/wavesplatform/WavesWallet-android/blob/master/app/src/main/AndroidManifest.xml)

**Comment by ZaydelEduard** [comment]
Hello @bodrych.

Thanks for your feedback. A Payment API is planned to be added soon..

**Comment by bodrych** [comment]
But when?

**Comment by ZaydelEduard** [comment]
As soon as possible. I can't give an exact date. Stay tuned

**Comment by ZaydelEduard** [comment]
@bodrych Hello

Since version [2.6.2](https://github.com/wavesplatform/WavesWallet-android/releases/tag/2.6.2) (current master branch) support all features from Payment API and deeplink for send/order.

Feel free to write feedback, 
Good luck
