### ISSUE TITLE
bad url at terms and conditions in Russian version

### ISSUE THREAD

**Issue by Kwaskoff** [wavesplatform/WavesWallet-android#418]
May be at another language versions too

**Comment by ZaydelEduard** [comment]
Hello @Kwaskoff 

Thanks for feedback, you are right. Now url for privacy policy is invalid. Will fix at 2.6.0 release.

**Comment by ZaydelEduard** [comment]
Fixed at [2.6.0 release](https://github.com/wavesplatform/WavesWallet-android/releases/tag/2.6.0)
