### ISSUE TITLE
api-keys.properties' as it does not exist

### ISSUE THREAD

**Issue by Mattiell0X** [wavesplatform/WavesWallet-android#483]
Hello guys, I downloaded

git clone https://github.com/wavesplatform/WavesWallet-android.git

And I'm using Android Studio to build it.

And it generates this error msg.

##########################################

14/01/20
11:08 Gradle sync started with single-variant sync

11:08 Gradle sync failed: Could not read script '/run/media/mattiellox/DATA/android-studio-ide-waves/WavesWallet-android/app/api-keys.properties' as it does not exist. (7 s 89 ms)

11:08 NDK Resolution Outcome: Project settings: Gradle model version=5.4.1, NDK version is UNKNOWN

11:23 Gradle sync started with single-variant sync

11:23 Gradle sync failed: Could not read script '/run/media/mattiellox/DATA/android-studio-ide-waves/WavesWallet-android/app/api-keys.properties' as it does not exist. (1 s 351 ms)

##########################################

He's asking for a file that doesn't exist inside the directory, and I didn't find a model for how I should create this file, can anyone help me?

 https://i.stack.imgur.com/Wl38z.png

**Comment by ZaydelEduard** [comment]
Hello @mrrobots 

Look at this issue https://github.com/wavesplatform/WavesWallet-android/issues/391

There is a section of code for this file. Insert your data and try to run the project again

**Comment by Mattiell0X** [comment]
OK tanks Man!

**Comment by ZaydelEduard** [comment]
You are welcome

If there are any problems - open the new issue
