### ISSUE TITLE
How to compile without google-services.json??

### ISSUE THREAD

**Issue by pedrofassis** [wavesplatform/WavesWallet-android#55]
How to compile without google-services.json??

**Comment by raqeta** [comment]
Hello, read [this](https://github.com/wavesplatform/WavesWallet-iOS/issues/68) iOS topic. It's about creation your own Firebase database. After it you can download google-services.json-file in Project Overview settings. Put it in "app" directory.

**Comment by pedrofassis** [comment]
Tks a lot, I'll try that!

Em qua, 5 de dez de 2018 11:46, Aleksandr Ershov <notifications@github.com<mailto:notifications@github.com> escreveu:

Hello, read this<https://github.com/wavesplatform/WavesWallet-iOS/issues/68> iOS topic. It's about creation your own Firebase database. After it you can download google-services.json-file in Project Overview settings. Put it in "app" directory.
