### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by djpnewton** [wavesplatform/WavesWallet-android#6]
There is no source code license? Is this project open source?

Also is this the code used to build https://play.google.com/store/apps/details?id=com.wavesplatform.wallet&hl=en ??

**Comment by br0x** [comment]
There IS source code license.
This project IS open source.
This code IS used to build official Android app you mentioned.

**Comment by djpnewton** [comment]
What license?

**Comment by br0x** [comment]
MIT license

**Comment by ericelliott** [comment]
Please add the LICENSE file to the project root directory.

**Comment by ZaydelEduard** [comment]
License added. Thank you all
