### ISSUE TITLE
CC payment UX issues.

### ISSUE THREAD

**Issue by ericelliott** [wavesplatform/WavesWallet-android#79]
The CC payment feature doesn't work in the US, and the 3rd party payment UI is terrible on mobile screens.

I'd rather not see the option for a credit card purchase than be dumped off into that 3rd party mess.

**Comment by raqeta** [comment]
Hello. Unfortunately, we cannot offer another service for credit card yet. We are aware of this problem and are working on it. But if you have any cryptocurrency, you can generate blockchain address in Receive-partition of application and send the cryptocurrency to it. Thank you for your feedback.

**Comment by ericelliott** [comment]
Maybe it's better not to display CC button to US-based customers at all?

**Comment by ericelliott** [comment]
Coinomat/Indacoin pops up a (very ugly, hard-to-read, not-correctly-formatted-on-mobile) modal message that says something like "Sorry. We can't serve customers in the United States."

If it works at all. I tried to get you an exact quote of the error message modal, but right now it's just giving me:

> `504 Gateway Time-out`

from nginx.

**Comment by ericelliott** [comment]
Ah, now it's "working" again.

What I can read of the error message says:

> "We sincerely apologize for the inconvenience but Indacoin doesn't operate in the US and can't..."

I can't read the rest because it's formatted so badly it runs off the bottom of the screen. 

![screenshot_20181206-123638](https://user-images.githubusercontent.com/364727/49610542-b9d2c580-f953-11e8-886e-28cd33b1a233.png)

**Comment by ZaydelEduard** [comment]
This is not problem of the app. 

Please contatct with support of our partners Сoinomat and Indacoin.

Thanks
